version: "3.3"
services:
  app_root_ds:
    volumes:
      - .:/app
      - ./stores/basic:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    environment:
      - LOADER=pandas
      - MOUNT_FOLDER=/app/data
      - BLOCK_NAME=CSV Block #  BlockSimple
      - BLOCK_LOADER=BlockLoaderFile # CSV Block
    ports:
      - "9080:80"
    command: [ "/app/start_dev.sh" ]
    networks:
      - ml-blocks-net

volumes:
  store-data-volume: null

networks:
  ml-blocks-net:
