version: "3.3"
services:

  app_root_ds:
    volumes:
      - .:/app
      - ./app/block:/app/app/block
      - ./stores/data_root:/app/data
      - ./requirements.txt:/app/requirements_local.txt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true

    environment:
      - LOADER=archive
    ports:
      - "9080:80"
    # command: [ "/app/start_dev.sh" ]
    command: ["/app/start.sh"]
    networks:
        - ml-blocks-net
        
volumes:
  store-data-volume: null

networks:
  ml-blocks-net:
