version: "3.3"
services:


  app_root_ds:
    volumes:
      - .:/app
      - ./app/custom:/app/app/custom
      - ./stores/data_root:/app/data
      - ./requirements.txt:/app/requirements_local.txt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true

    environment:
      - LOADER=archive
    ports:
      - "9080:80"
    command: [ "/app/start_dev.sh" ]
    # command: ["/app/start.sh"]
    networks:
        - ml-blocks-net

  app_root_dep_1:
    volumes:
      - .:/app
      - ./app/custom:/app/app/custom
      - ./stores/data_root_dep_1:/app/data
      - ./requirements.txt:/app/requirements_local.txt
    links:
      - "app_root_ds:app_root_ds"
    environment:
      DEPENDENCY_BLOCK: app_root_ds
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    ports:
      - "9081:80"
    command: [ "/app/start_dev.sh" ]
    # command: ["/app/start.sh"]
    networks:
        - ml-blocks-net  
  
volumes:
  store-data-volume: null

networks:
  ml-blocks-net:
    driver: bridge