version: "3.3"
services:

  root_block:
    volumes:
      - .:/app 
      - ./stores/ds_root:/app/data
      - ./samples/file-loader:/app/app/block      
      # - ./samples/file-loader/requirements.txt:/app/requirements_local.txt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    environment:
      - LOADER=pandas
    ports:
      - "9080:80"
    command: [ "/app/start_dev.sh" ]
    networks:
      - ml-blocks-net

  link1:
    volumes:
      - .:/app
      - ./stores/link1:/app/data
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    environment:
      - REGISTRY=root_block
      - DATA_DEPENDENCY=root_block
    ports:
      - "9081:80"
    command: [ "/app/start_dev.sh" ]
    # command: [ "/app/start.sh" ]
    networks:
      - ml-blocks-net

  link2:
    depends_on:
      - link1
    volumes:
      - .:/app
      - ./stores/ds_root_d2:/app/data
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    ports:
      - "9082:80"
    environment:
      - REGISTRY=root_block
      - DATA_DEPENDENCY=link1
    command: [ "/app/start_dev.sh" ]
    # command: [ "/app/start.sh" ]
    networks:
      - ml-blocks-net

volumes:
  store-data-volume: null

networks:
  ml-blocks-net:
